# Generated by Django 5.1.3 on 2024-11-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_whychooseus'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='icons_img',
            field=models.ImageField(blank=True, null=True, upload_to='icons_img/'),
        ),
    ]
