# Generated by Django 5.1.3 on 2024-11-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='snapchat',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='icon_social',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='social_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
