# Generated by Django 5.1.3 on 2024-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_remove_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
