# Generated by Django 5.1.3 on 2024-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_remove_whychooseus_icons_img_whychooseus_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseus',
            name='icons',
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='icons_img',
            field=models.ImageField(blank=True, null=True, upload_to='icons_img/'),
        ),
    ]
