# Generated by Django 5.1.3 on 2024-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_remove_whychooseus_icons_whychooseus_icons_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='icon_color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
