# Generated by Django 5.1.3 on 2024-11-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0002_customuser_delete_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
