# Generated by Django 5.1.3 on 2024-11-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='user',
        ),
    ]
