# Generated by Django 5.1.3 on 2024-11-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_flow', '0008_alter_allusers_options_alter_allusers_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllUsers',
            new_name='User',
        ),
    ]
