# Generated by Django 5.1.3 on 2024-11-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0010_rename_user_allusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allusers',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='allusers',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allusers',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='allusers',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
