# Generated by Django 5.1.3 on 2024-11-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0011_rename_phone_allusers_phone_number_allusers_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='city',
        ),
        migrations.RemoveField(
            model_name='allusers',
            name='country',
        ),
    ]
