# Generated by Django 5.1.3 on 2024-11-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0012_remove_allusers_city_remove_allusers_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allusers',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
