# Generated by Django 5.1.3 on 2024-11-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0013_rename_phone_number_allusers_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='address',
        ),
    ]
