# Generated by Django 5.1.3 on 2024-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0014_remove_allusers_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('User', 'User')], default='User', max_length=10),
        ),
    ]
