# Generated by Django 5.1.3 on 2024-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0015_allusers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('User', 'User')], default='User', max_length=10, null=True),
        ),
    ]
