# Generated by Django 5.1.3 on 2024-11-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0016_alter_allusers_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='allusers',
            managers=[
            ],
        ),
    ]
