# Generated by Django 5.1.3 on 2024-11-22 20:02

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0017_alter_allusers_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='allusers',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
