# Generated by Django 5.1.3 on 2024-11-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0019_alter_allusers_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='user_permissions',
        ),
    ]
