# Generated by Django 5.1.3 on 2024-11-22 20:49

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0021_alter_allusers_managers_allusers_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='allusers',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='allusers',
            name='permissions',
        ),
    ]
