# Generated by Django 5.1.3 on 2024-11-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0024_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='positon',
            new_name='position',
        ),
    ]
