# Generated by Django 5.1.3 on 2024-11-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0025_rename_positon_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
