# Generated by Django 5.1.3 on 2024-11-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0026_rename_comapny_name_employee_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
