# Generated by Django 5.1.3 on 2024-11-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0027_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
