# Generated by Django 5.1.3 on 2024-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0028_remove_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
