# Generated by Django 5.1.3 on 2024-12-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0031_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
