# Generated by Django 5.1.3 on 2024-12-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0032_employee_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.AddField(
            model_name='allusers',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
