# Generated by Django 5.1.3 on 2024-12-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_flow', '0033_remove_employee_full_name_allusers_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='full_name',
        ),
    ]
