# Generated by Django 5.1.3 on 2024-11-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestep',
            name='data_req_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
