# Generated by Django 5.1.3 on 2024-11-26 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0002_servicestep_data_req_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestep',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps_order', to='our_service.serviceorder'),
            preserve_default=False,
        ),
    ]
