# Generated by Django 5.1.3 on 2024-11-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0006_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected')], default='In Progress', max_length=255),
        ),
    ]
