# Generated by Django 5.1.3 on 2024-11-28 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0008_alter_serviceorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='pending', max_length=255)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=255)),
                ('step_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='our_service.serviceorder')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_service.servicestep')),
            ],
        ),
    ]
