# Generated by Django 5.1.3 on 2024-11-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0009_serviceorderstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderstep',
            name='data_req_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderstep',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='service_steps/'),
        ),
        migrations.AddField(
            model_name='serviceorderstep',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceorderstep',
            name='requirements_files',
            field=models.TextField(blank=True, null=True),
        ),
    ]
