# Generated by Django 5.1.3 on 2024-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0010_serviceorderstep_data_req_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benifits_service',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image_service',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
