# Generated by Django 5.1.3 on 2024-12-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0011_service_benifits_service_service_image_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestep',
            name='data_user_file_upload',
            field=models.FileField(blank=True, null=True, upload_to='service_steps/'),
        ),
    ]
