# Generated by Django 5.1.3 on 2024-12-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0012_servicestep_data_user_file_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorderstep',
            old_name='requirements_files',
            new_name='requirements_data_from_user',
        ),
        migrations.RenameField(
            model_name='servicestep',
            old_name='requirements_files',
            new_name='requirements_data_from_user',
        ),
    ]
