# Generated by Django 5.1.3 on 2024-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0013_rename_requirements_files_serviceorderstep_requirements_data_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderstep',
            name='data_user_file_upload',
            field=models.FileField(blank=True, null=True, upload_to='service_steps/'),
        ),
    ]
