# Generated by Django 5.1.3 on 2024-12-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0015_service_icon_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderstep',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorderstep',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='pending', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorderstep',
            name='step_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicestep',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicestep',
            name='step_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
