# Generated by Django 5.1.3 on 2024-12-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0018_alter_service_icon_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
