# Generated by Django 5.1.3 on 2024-12-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_service', '0021_alter_serviceorderstep_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderstep',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('in_progress', 'In Progress'), ('paid', 'Paid')], default='unpaid', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicestep',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('in_progress', 'In Progress'), ('paid', 'Paid')], default='unpaid', max_length=255, null=True),
        ),
    ]
