# Generated by Django 5.1.3 on 2024-12-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='id_package',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
