# Generated by Django 5.1.3 on 2024-11-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
