# Generated by Django 5.1.3 on 2024-11-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
