# Generated by Django 5.1.3 on 2024-11-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category_name',
        ),
    ]
