"""
Django settings for waslBackendProject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!ydksbv^4xa_jpo6q$rix7q@(e)zjy8n7mfr$8y7)jjkl&0-qw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    # Add Auth App
    'auth_flow.apps.AuthFlowConfig',
    # Home App
    'home_app.apps.HomeAppConfig',
    # Contact US App
    'contact_us.apps.ContactUsConfig',
    # Packages App
    'packages.apps.PackagesConfig',
    # Add About App
    'about_us.apps.AboutUsConfig',
    # Blog App
    'blog.apps.BlogConfig',
    # Add Django Filter
    'django_filters',
    #Add Services App
    'our_service.apps.OurServiceConfig',
    # Cors Headers
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',                # Django REST framework for building APIs
    'rest_framework_simplejwt',      # SimpleJWT for handling JWT authentication
]

# CORS Headers Configuration
CORS_ALLOWED_ORIGINS = [
    "https://example.com",
    "http://localhost:3000",
]
# Use CORS_ALLOW_ALL_ORIGINS = True for unrestricted access (not recommended for production).
CORS_ALLOW_ALL_ORIGINS = True



# REST Framework configuration with JWT authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Use JWT authentication as default
    ),
}

AUTH_USER_MODEL = 'auth_flow.AllUsers'



# JWT settings: token expiration times and Bearer prefix
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),    # Access token valid for 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),      # Refresh token valid for 1 day
    'AUTH_HEADER_TYPES': ('Bearer',),                 # Use 'Bearer' in the Authorization header
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Cors Headers Middleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

ROOT_URLCONF = 'waslBackendProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'waslBackendProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Ensure this points to the directory with your custom static files (if any)
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# pyotp settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Development use only

# OR Use SMTP for production
# settings.py

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # Or any SMTP service you're using
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'lotfymh9@gmail.com'  # Your email here
# EMAIL_HOST_PASSWORD = '0987654321Mohamed$'  # App password or your real password
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# DEFAULT_FROM_EMAIL = 'lotfy1654@gmail.com'



# For production use, you should use environment variables to store sensitive information

CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = False  # For development; set to True when using HTTPS in production
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'  # or 'Strict' for stricter enforcement
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_SECURE = False  # For development; set to True for HTTPS in production